version: '3.8'

services:
  db:
    container_name: postgres-esg
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: esgbot
    env_file:
      - ".env"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  redis:
    container_name: redis-esg
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/var/lib/redis/data
  bot:
    container_name: bot
    build: .
    restart: always
    env_file:
      - ".env"
    depends_on:
      - "db"
      - 'redis'
volumes:
  postgres-db:
  redis:
